spring.application.name=crm-spring-boot

app.dynamodb.region=us-east-1
app.dynamodb.entity-a-table=entity_a
app.dynamodb.entity-b-table=entity_b
app.dynamodb.entity-c-table=entity_c
# Optional for local testing (e.g. http://localhost:8000)
# app.dynamodb.endpoint=
